// Copyright (c) 2026 WhoseBiasDoYallSeek
// SPDX-License-Identifier: MIT
// See LICENSE file for full text.
//
// Package cgogen generates idiomatic Go wrapper files (via CGo) from
// parsed C header function declarations.
//
// Pattern produced for each C function:
//
//	// Fft wraps mlx_fft_fft.
//	func Fft(a Array, n int, axis int, norm FftNorm, s Stream) (Array, error) {
//	    var _res C.mlx_array
//	    _err := C.mlx_fft_fft(&_res, a.c, C.int(n), C.int(axis), C.mlx_fft_norm(norm), s.c)
//	    if _err != 0 {
//	        return Array{}, mlxError(_err)
//	    }
//	    return Array{_res}, nil
//	}
package cgogen

import (
	"fmt"
	"strings"
	"unicode"

	"github.com/WhoseBiasDoYallSeek/mlx-cgo/internal/cheader"
)

// Options controls code generation.
type Options struct {
	// PackageName is the Go package name written to the file header.
	PackageName string
	// Imports is the list of additional Go imports to add.
	Imports []string
}

// GenerateGoFile returns the content of a .go file wrapping all functions
// in cfuncs for the given Go package name.
func GenerateGoFile(cfuncs []cheader.CFunc, opts Options) string {
	var b strings.Builder

	pkg := opts.PackageName
	if pkg == "" {
		pkg = "mlx"
	}

	// Check if any params need the "unsafe" import.
	// IsRawVecPtr → unsafe.Pointer(&slice[0])
	// const char* → C.free(unsafe.Pointer(_cstr_...))
	needsUnsafe := false
	for _, fn := range cfuncs {
		for _, p := range fn.Params {
			if p.IsRawVecPtr {
				needsUnsafe = true
			}
			t := strings.TrimPrefix(strings.TrimSpace(p.Type), "const ")
			if strings.TrimSpace(t) == "char*" {
				needsUnsafe = true
			}
		}
	}

	b.WriteString("// Code generated by mlxgen; DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "package %s\n\n", pkg)

	// CGo preamble
	b.WriteString("/*\n")
	b.WriteString("#cgo LDFLAGS: -lmlx-c\n")
	b.WriteString("#include <mlx/c/mlx.h>\n")
	b.WriteString("*/\n")
	b.WriteString("import \"C\"\n\n")

	b.WriteString("import (\n")
	b.WriteString("\t\"fmt\"\n")
	if needsUnsafe {
		b.WriteString("\t\"unsafe\"\n")
	}
	for _, imp := range opts.Imports {
		fmt.Fprintf(&b, "\t%q\n", imp)
	}
	b.WriteString(")\n\n")

	b.WriteString("func mlxError(code C.int) error {\n")
	b.WriteString("\treturn fmt.Errorf(\"mlx error: code %d\", int(code))\n")
	b.WriteString("}\n\n")

	for _, fn := range cfuncs {
		writeWrapper(&b, fn)
		b.WriteString("\n")
	}

	return b.String()
}

// writeWrapper writes a single Go function wrapper.
func writeWrapper(b *strings.Builder, fn cheader.CFunc) {
	goName := toGoFuncName(fn.Name)
	if goName == "" {
		return
	}

	var retParams, inParams []cheader.CParam
	for _, p := range fn.Params {
		if p.IsReturn {
			retParams = append(retParams, p)
		} else if !p.IsRawVecLen { // skip size_t len params — folded into []T
			inParams = append(inParams, p)
		}
	}

	// Build Go input signature
	var goIns []string
	for _, p := range inParams {
		var gt string
		if p.IsRawVecPtr {
			gt = "[]" + rawVecGoElem(p.RawVecElem)
		} else {
			gt = cTypeToGo(p.Type)
		}
		name := sanitizeName(p.Name)
		if name == "" {
			name = "_p" + fmt.Sprint(len(goIns))
		}
		goIns = append(goIns, name+" "+gt)
	}

	// Build Go return types
	var goRets []string
	for _, p := range retParams {
		goRets = append(goRets, cRetTypeToGo(p.Type))
	}
	goRets = append(goRets, "error")

	// Comment + signature
	fmt.Fprintf(b, "// %s wraps %s.\n", goName, fn.Name)
	fmt.Fprintf(b, "func %s(%s) (%s) {\n",
		goName,
		strings.Join(goIns, ", "),
		strings.Join(goRets, ", "),
	)

	// Declare return vars
	for i, p := range retParams {
		fmt.Fprintf(b, "\tvar _res%d %s\n", i, cToCGoType(p.Type))
	}

	// Pre-call setup:
	//   - slice params: guard &slice[0] against empty slice → nil-safe _ptr_NAME var.
	//   - string params: C.CString allocates on C heap; always free via defer.
	for _, p := range inParams {
		name := sanitizeName(p.Name)
		if p.IsRawVecPtr {
			celem := "C." + p.RawVecElem
			fmt.Fprintf(b, "\tvar _ptr_%s *%s\n", name, celem)
			fmt.Fprintf(b, "\tif len(%s) > 0 {\n", name)
			fmt.Fprintf(b, "\t\t_ptr_%s = (*%s)(unsafe.Pointer(&%s[0]))\n", name, celem, name)
			fmt.Fprintf(b, "\t}\n")
			continue
		}
		t := strings.TrimPrefix(strings.TrimSpace(p.Type), "const ")
		t = strings.TrimSpace(t)
		switch t {
		case "char*":
			fmt.Fprintf(b, "\t_cstr_%s := C.CString(%s)\n", name, name)
			fmt.Fprintf(b, "\tdefer C.free(unsafe.Pointer(_cstr_%s))\n", name)
		case "int*", "float*", "double*", "bool*":
			celem := "C." + strings.TrimSuffix(t, "*")
			fmt.Fprintf(b, "\tvar _ptr_%s *%s\n", name, celem)
			fmt.Fprintf(b, "\tif len(%s) > 0 {\n", name)
			fmt.Fprintf(b, "\t\t_ptr_%s = (*%s)(unsafe.Pointer(&%s[0]))\n", name, celem, name)
			fmt.Fprintf(b, "\t}\n")
		}
	}

	// Build C call arguments
	var callArgs []string
	for i := range retParams {
		callArgs = append(callArgs, fmt.Sprintf("&_res%d", i))
	}
	for _, p := range inParams {
		name := sanitizeName(p.Name)
		if p.IsRawVecPtr {
			// Pre-call guard already emitted above; reference the _ptr_ var.
			callArgs = append(callArgs,
				fmt.Sprintf("_ptr_%s, C.size_t(len(%s))", name, name),
			)
		} else {
			callArgs = append(callArgs, goToCGo(name, p.Type))
		}
	}

	fmt.Fprintf(b, "\t_err := C.%s(%s)\n", fn.Name, strings.Join(callArgs, ", "))

	// Error check
	b.WriteString("\tif _err != 0 {\n")
	var zeroRets []string
	for _, p := range retParams {
		zeroRets = append(zeroRets, zeroValue(p.Type))
	}
	zeroRets = append(zeroRets, "mlxError(_err)")
	fmt.Fprintf(b, "\t\treturn %s\n", strings.Join(zeroRets, ", "))
	b.WriteString("\t}\n")

	// Return
	var retExprs []string
	for i, p := range retParams {
		retExprs = append(retExprs, cgoToGo(fmt.Sprintf("_res%d", i), p.Type))
	}
	retExprs = append(retExprs, "nil")
	fmt.Fprintf(b, "\treturn %s\n", strings.Join(retExprs, ", "))

	b.WriteString("}\n")
}

// rawVecGoElem returns the Go element type for a raw C element type.
func rawVecGoElem(celem string) string {
	switch celem {
	case "int":
		return "int32"
	case "float":
		return "float32"
	case "double":
		return "float64"
	case "bool":
		return "bool"
	}
	return celem
}

// sanitizeName makes a C param name safe to use as a Go identifier.
func sanitizeName(name string) string {
	// Avoid Go keywords
	switch name {
	case "type", "func", "map", "range", "select", "var", "go", "chan", "return":
		return name + "_"
	}
	return name
}

// toGoFuncName converts "mlx_fft_fft" to "FftFft", "mlx_abs" → "Abs", etc.
// Removes the "mlx_" prefix and title-cases each segment.
func toGoFuncName(cname string) string {
	s := strings.TrimPrefix(cname, "mlx_")
	// Skip internal helpers (_free, _new, _set, etc.)
	parts := strings.Split(s, "_")
	if len(parts) == 0 {
		return ""
	}
	var b strings.Builder
	for _, p := range parts {
		if p == "" {
			continue
		}
		r := []rune(p)
		r[0] = unicode.ToUpper(r[0])
		b.WriteString(string(r))
	}
	return b.String()
}

// cTypeToGo returns the idiomatic Go type for a C input parameter type.
func cTypeToGo(ctype string) string {
	// Strip "const " prefix
	t := strings.TrimPrefix(strings.TrimSpace(ctype), "const ")
	t = strings.TrimSpace(t)
	switch t {
	case "mlx_array":
		return "Array"
	case "mlx_stream":
		return "Stream"
	case "mlx_device":
		return "Device"
	case "mlx_dtype":
		return "Dtype"
	case "mlx_closure":
		return "Closure"
	case "mlx_closure_kwargs":
		return "ClosureKwargs"
	case "mlx_vector_array":
		return "VectorArray"
	case "mlx_map_string_to_array":
		return "MapStringToArray"
	case "mlx_map_string_to_string":
		return "MapStringToString"
	case "mlx_distributed_group":
		return "DistributedGroup"
	case "mlx_string":
		return "MLXString"
	case "int":
		return "int"
	case "float":
		return "float32"
	case "double":
		return "float64"
	case "bool":
		return "bool"
	case "size_t", "uint64_t":
		return "uint64"
	case "int64_t":
		return "int64"
	case "int32_t":
		return "int32"
	case "uintptr_t":
		return "uintptr"
	case "const char*", "char*":
		return "string"
	case "const int*":
		return "[]int32"
	case "const float*":
		return "[]float32"
	case "mlx_complex64_t":
		return "complex64"
	}
	// Enum types (e.g. mlx_fft_norm)
	if strings.HasPrefix(t, "mlx_") {
		return toCamelCase(strings.TrimPrefix(t, "mlx_"))
	}
	return t
}

// cRetTypeToGo returns the Go type for a C return (out-param pointer) type.
// e.g. "mlx_array*" → "Array"
func cRetTypeToGo(ctype string) string {
	t := strings.TrimSuffix(strings.TrimSpace(ctype), "*")
	t = strings.TrimSpace(t)
	return cTypeToGo(t)
}

// cToCGoType returns the CGo type for a C return var declaration.
func cToCGoType(ctype string) string {
	t := strings.TrimSuffix(strings.TrimSpace(ctype), "*")
	t = strings.TrimPrefix(strings.TrimSpace(t), "const ")
	return "C." + strings.TrimSpace(t)
}

// goToCGo converts a Go variable to its CGo form for a C call argument.
func goToCGo(name, ctype string) string {
	t := strings.TrimPrefix(strings.TrimSpace(ctype), "const ")
	t = strings.TrimSpace(t)
	switch t {
	case "mlx_array", "mlx_stream", "mlx_device", "mlx_closure",
		"mlx_closure_kwargs", "mlx_vector_array", "mlx_map_string_to_array",
		"mlx_map_string_to_string", "mlx_distributed_group":
		return name + ".c"
	case "int":
		return "C.int(" + name + ")"
	case "float":
		return "C.float(" + name + ")"
	case "double":
		return "C.double(" + name + ")"
	case "bool":
		return "C.bool(" + name + ")"
	case "size_t":
		return "C.size_t(" + name + ")"
	case "int64_t":
		return "C.int64_t(" + name + ")"
	case "mlx_dtype":
		return "C.mlx_dtype(" + name + ")"
	case "const char*", "char*":
		return "_cstr_" + name
	// These are non-raw-vec pointer params (no paired size_t). The pre-call
	// setup emits a nil-safe _ptr_NAME guard; reference it here.
	case "int*", "float*", "double*", "bool*":
		return "_ptr_" + name
	}
	if strings.HasPrefix(t, "mlx_") {
		return "C." + t + "(" + name + ")"
	}
	return "C." + t + "(" + name + ")"
}

// cgoToGo converts a CGo result variable to its Go form.
func cgoToGo(expr, ctype string) string {
	t := strings.TrimSuffix(strings.TrimSpace(ctype), "*")
	t = strings.TrimSpace(t)
	switch t {
	case "mlx_array":
		return "Array{" + expr + "}"
	case "mlx_stream":
		return "Stream{" + expr + "}"
	case "mlx_device":
		return "Device{" + expr + "}"
	case "mlx_closure":
		return "Closure{" + expr + "}"
	case "mlx_vector_array":
		return "VectorArray{" + expr + "}"
	case "mlx_map_string_to_array":
		return "MapStringToArray{" + expr + "}"
	case "int":
		return "int(" + expr + ")"
	case "float":
		return "float32(" + expr + ")"
	case "double":
		return "float64(" + expr + ")"
	case "bool":
		return "bool(" + expr + ")"
	case "mlx_dtype":
		return "Dtype(" + expr + ")"
	}
	if strings.HasPrefix(t, "mlx_") {
		return toCamelCase(strings.TrimPrefix(t, "mlx_")) + "{" + expr + "}"
	}
	return expr
}

// zeroValue returns the Go zero value expression for a C return type.
func zeroValue(ctype string) string {
	t := strings.TrimSuffix(strings.TrimSpace(ctype), "*")
	switch t {
	case "int":
		return "0"
	case "float":
		return "0"
	case "double":
		return "0"
	case "bool":
		return "false"
	}
	gt := cRetTypeToGo(ctype)
	return gt + "{}"
}

// toCamelCase converts snake_case to CamelCase.
func toCamelCase(s string) string {
	parts := strings.Split(s, "_")
	var b strings.Builder
	for _, p := range parts {
		if p == "" {
			continue
		}
		r := []rune(p)
		r[0] = unicode.ToUpper(r[0])
		b.WriteString(string(r))
	}
	return b.String()
}
