package cgogen

import (
	"fmt"
	"strings"
)

// opaqueHandle describes a Go struct wrapping a C opaque handle.
type opaqueHandle struct {
	goName string // e.g. "Array"
	cName  string // e.g. "mlx_array"
}

// coreHandles are the fundamental opaque types exposed in the Go package.
// These correspond to the opaqueType entries in internal/types/ctypes.go that
// appear as parameters or return values in the public C API.
var coreHandles = []opaqueHandle{
	{"Array", "mlx_array"},
	{"Stream", "mlx_stream"},
	{"Device", "mlx_device"},
	{"Closure", "mlx_closure"},
	{"ClosureValueAndGrad", "mlx_closure_value_and_grad"},
	{"ClosureCustom", "mlx_closure_custom"},
	{"ClosureCustomJvp", "mlx_closure_custom_jvp"},
	{"ClosureCustomVmap", "mlx_closure_custom_vmap"},
	{"VectorArray", "mlx_vector_array"},
	{"VectorInt", "mlx_vector_int"},
	{"VectorString", "mlx_vector_string"},
	{"MapStringToArray", "mlx_map_string_to_array"},
	{"MapStringToString", "mlx_map_string_to_string"},
	{"DistributedGroup", "mlx_distributed_group"},
}

// GenerateGoBase produces the base Go file for a CGo package.
// It emits:
//   - The CGo preamble that includes mlx/c/mlx.h
//   - Opaque struct definitions for every MLX handle type
//   - Constructor helpers (newXxx) and a Free method for each
//   - A Dtype type alias
//
// The generated file is intended to live alongside the function wrapper files
// produced by GenerateGoFile (e.g. in mlx/go/).
func GenerateGoBase(pkgName string) string {
	var b strings.Builder
	p := func(format string, args ...any) {
		fmt.Fprintf(&b, format+"\n", args...)
	}

	p(`// Code generated by mlxgen --type=go-base. DO NOT EDIT.`)
	p(``)
	p(`package %s`, pkgName)
	p(``)
	p(`/*`)
	p(`#cgo CFLAGS: -I${SRCDIR}/../../`)
	p(`#cgo LDFLAGS: -lmlxc`)
	p(`#include "mlx/c/mlx.h"`)
	p(`#include <stdlib.h>`)
	p(`*/`)
	p(`import "C"`)
	p(``)
	p(`import "fmt"`)
	p(``)
	p(`// Dtype represents an MLX data type.`)
	p(`type Dtype = C.mlx_dtype`)
	p(``)
	p(`// Dtype constants mirror the mlx_dtype C enum.`)
	p(`const (`)
	p(`	Bool    Dtype = C.mlx_bool`)
	p(`	Uint8   Dtype = C.mlx_uint8`)
	p(`	Uint16  Dtype = C.mlx_uint16`)
	p(`	Uint32  Dtype = C.mlx_uint32`)
	p(`	Uint64  Dtype = C.mlx_uint64`)
	p(`	Int8    Dtype = C.mlx_int8`)
	p(`	Int16   Dtype = C.mlx_int16`)
	p(`	Int32   Dtype = C.mlx_int32`)
	p(`	Int64   Dtype = C.mlx_int64`)
	p(`	Float16 Dtype = C.mlx_float16`)
	p(`	Float32 Dtype = C.mlx_float32`)
	p(`	Bfloat16 Dtype = C.mlx_bfloat16`)
	p(`	Complex64 Dtype = C.mlx_complex64`)
	p(`)`)
	p(``)

	// Generate opaque structs and constructors
	for _, h := range coreHandles {
		p(`// %s wraps a C.%s opaque handle.`, h.goName, h.cName)
		p(`// Memory is owned by the caller: call Free when done.`)
		p(`type %s struct { c C.%s }`, h.goName, h.cName)
		p(``)
		p(`func new%s(c C.%s) %s { return %s{c: c} }`, h.goName, h.cName, h.goName, h.goName)
		p(``)
		p(`// Free releases the C wrapper. The underlying C++ tensor data is managed`)
		p(`// by the MLX C++ runtime (shared_ptr refcount) and may outlive this call.`)
		p(`// Idiomatic usage: defer result.Free()`)
		p(`func (v %s) Free() { C.%s_free(v.c) }`, h.goName, h.cName)
		p(``)
	}

	// Default stream/device helpers
	p(`// DefaultStream returns the default MLX stream for the default device.`)
	p(`func DefaultStream() Stream { return new%s(C.mlx_default_stream(C.mlx_default_device())) }`, "Stream")
	p(``)
	p(`// DefaultDevice returns the default MLX device.`)
	p(`func DefaultDevice() Device { return new%s(C.mlx_default_device()) }`, "Device")
	p(``)

	// mlxError helper used by all generated wrappers
	p(`// mlxError returns the last MLX error as a Go error.`)
	p(`func mlxError(name string, code C.int) error {`)
	p(`	return fmt.Errorf("%%s failed (code %%d)", name, int(code))`)
	p(`}`)
	p(``)

	return b.String()
}
